/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Allchat: typeof import('./components/Allchat.vue')['default']
    Calendar: typeof import('./components/Calendar.vue')['default']
    Filterchat: typeof import('./components/Filterchat.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchbar: typeof import('./components/Searchbar.vue')['default']
  }
}
